# Generated by Django 4.1.4 on 2022-12-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelwithfilefield3',
            name='fileimg',
            field=models.FileField(upload_to='xyz'),
        ),
    ]
