# Generated by Django 4.1.4 on 2022-12-14 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_modelwithfilefield3_fileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelwithfilefield3',
            name='fileimg',
            field=models.FileField(upload_to='xyz', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg'])]),
        ),
    ]
